spring:
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          google:
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile


#
